name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOMAIN_NAME: stuartizon.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy infrastructure
        run: |
          terraform init infra
          terraform apply -auto-approve infra
        env:
          TF_VAR_domain_name: ${{ env.DOMAIN_NAME }}
      - name: Deploy code
        run: npm run deploy
